name: sucos_pocket
channels:
  - bioconda
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - alsa-lib=1.2.15.3=he30d5cf_0
  - aria2=1.37.0=h8372482_3
  - attr=2.5.1=h4e544f5_1
  - blosc=1.21.6=hb4dfabd_1
  - brotli=1.2.0=hd651790_1
  - brotli-bin=1.2.0=he30d5cf_1
  - bzip2=1.0.8=h4777abc_9
  - c-ares=1.34.6=he30d5cf_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h83712da_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h04741b4_4
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h6c5dea3_0
  - dbus=1.16.2=h70963c4_1
  - foldseek=10.941cd33=h3af90e8_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=hba86a56_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h164a683_0
  - freetype=2.14.1=h8af1aa0_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gawk=5.3.1=h01806b3_0
  - glew=2.2.0=h4f43aa7_0
  - glib=2.86.4=hc66a092_0
  - glib-tools=2.86.4=hc87f4d4_0
  - glm=1.0.1=h0fdc8fb_0
  - gmp=6.3.0=h0a1ffab_2
  - graphite2=1.3.14=hfae3067_2
  - greenlet=3.3.2=py311h8e4e6a5_0
  - gst-plugins-base=1.24.11=h83ffb7f_0
  - gstreamer=1.24.11=h17c303d_0
  - harfbuzz=12.2.0=he4899c9_0
  - hdf4=4.2.15=hb6ba311_7
  - hdf5=1.14.6=nompi_hf95b8e7_106
  - icu=75.1=hf9b3779_0
  - keyutils=1.6.3=h86ecc28_0
  - kiwisolver=1.4.9=py311h229e7f7_2
  - krb5=1.21.3=h50a48e9_0
  - lame=3.100=h4e544f5_1003
  - lcms2=2.18=h9d5b58d_0
  - ld_impl_linux-aarch64=2.45.1=default_h1979696_101
  - lerc=4.0.0=hfdc4d58_1
  - libaec=1.1.5=hff7e48a_0
  - libasprintf=0.25.1=h5e0f5ae_0
  - libblas=3.11.0=5_haddc8a3_openblas
  - libboost=1.86.0=h6339299_4
  - libboost-python=1.86.0=py311hbf824a7_5
  - libbrotlicommon=1.2.0=he30d5cf_1
  - libbrotlidec=1.2.0=he30d5cf_1
  - libbrotlienc=1.2.0=he30d5cf_1
  - libcap=2.77=h68e9139_0
  - libcblas=3.11.0=5_hd72aa62_openblas
  - libclang-cpp20.1=20.1.8=default_he95a3c9_8
  - libclang13=21.1.0=default_h94a09a5_1
  - libcups=2.3.3=h5cdc715_5
  - libcurl=8.18.0=h7bfdcfb_0
  - libdeflate=1.25=h1af38f5_0
  - libdrm=2.4.125=he30d5cf_1
  - libedit=3.1.20250104=pl5321h976ea20_0
  - libegl=1.7.0=hd24410f_2
  - libev=4.33=h31becfc_2
  - libevent=2.1.12=h4ba1bb4_1
  - libexpat=2.7.4=hfae3067_0
  - libffi=3.5.2=h376a255_0
  - libflac=1.5.0=he9c94f4_1
  - libfreetype=2.14.1=h8af1aa0_0
  - libfreetype6=2.14.1=hdae7a39_0
  - libgcc=15.2.0=h8acb6b2_17
  - libgcc-ng=15.2.0=he9431aa_17
  - libgettextpo=0.25.1=h5ad3122_0
  - libgfortran=15.2.0=he9431aa_18
  - libgfortran5=15.2.0=h1b7bec0_18
  - libgl=1.7.0=hd24410f_2
  - libglib=2.86.4=hf53f6bf_0
  - libglu=9.0.3=h5ad3122_1
  - libglvnd=1.7.0=hd24410f_2
  - libglx=1.7.0=hd24410f_2
  - libgomp=15.2.0=h8acb6b2_17
  - libiconv=1.18=h90929bb_2
  - libjpeg-turbo=3.1.2=he30d5cf_0
  - liblapack=3.11.0=5_h88aeb00_openblas
  - libllvm20=20.1.8=h2b567e5_0
  - libllvm21=21.1.0=h2b567e5_0
  - liblzma=5.8.2=he30d5cf_0
  - libnetcdf=4.9.3=nompi_hd58bea6_102
  - libnghttp2=1.67.0=ha888d0e_0
  - libnsl=2.0.1=h86ecc28_1
  - libntlm=1.4=hf897c2e_1002
  - libogg=1.3.5=h86ecc28_1
  - libopenblas=0.3.30=pthreads_h9d3fd7e_4
  - libopengl=1.7.0=hd24410f_2
  - libopus=1.6.1=h80f16a2_0
  - libpciaccess=0.18=h86ecc28_0
  - libpng=1.6.55=h1abf092_0
  - libpq=17.7=haf03d9f_1
  - librdkit=2025.03.6=h455954b_0
  - libsndfile=1.2.2=h30591a0_2
  - libsqlite=3.51.2=h022381a_0
  - libssh2=1.11.1=h18c354c_0
  - libstdcxx=15.2.0=hef695bb_17
  - libstdcxx-ng=15.2.0=hdbbeba8_17
  - libsystemd0=259.1=h8c5a66d_0
  - libtiff=4.7.1=hdb009f0_1
  - libuuid=2.41.3=h1022ec0_0
  - libvorbis=1.3.7=h7ac5ae9_2
  - libwebp-base=1.6.0=ha2e29f5_0
  - libxcb=1.17.0=h262b8f6_0
  - libxcrypt=4.4.36=h31becfc_1
  - libxkbcommon=1.11.0=h95ca766_0
  - libxml2=2.13.9=he58860d_0
  - libzip=1.11.2=h3e8f909_0
  - libzlib=1.3.1=h86ecc28_2
  - lz4-c=1.10.0=h5ad3122_1
  - matplotlib-base=3.10.8=py311hb9c6b48_0
  - mmseqs2=18.8cc5c=h7645e38_0
  - mpfr=4.2.1=h2305555_3
  - mpg123=1.32.9=h65af167_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=ha32ae93_3
  - nspr=4.38=h3ad9384_0
  - nss=3.118=h544fa81_0
  - numpy=2.4.2=py311h669026d_1
  - openjpeg=2.5.4=h5da879a_0
  - openldap=2.6.10=h30c48ee_0
  - openssl=3.6.1=h546c87b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.1=py311h6a55483_0
  - pcre2=10.47=hf841c20_0
  - pillow=12.1.1=py311h8e17b9e_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h7ac5ae9_1
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.1.1=py311hec3470c_0
  - pthread-stubs=0.4=h86ecc28_1002
  - pulseaudio-client=17.0=hcf98165_3
  - pycairo=1.29.0=py311h988189f_1
  - pymol-open-source=3.1.0=py311h5ba4ff7_2
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py311h4808784_2
  - pyqt5-sip=12.17.0=py311h2cb90db_2
  - python=3.11.14=h91f4b29_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h70be974_5
  - qt-main=5.15.15=hbe73643_5
  - rdkit=2025.03.6=py311hffe688f_0
  - readline=8.3=hb682ff5_0
  - reportlab=4.4.10=pyhcf101f3_1
  - rlpycairo=0.4.0=pyh6c17108_0
  - setuptools=82.0.0=pyh332efcf_0
  - sip=6.15.0=py311h0cfd530_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=he774c54_1
  - sqlalchemy=2.0.46=py311had3b7ee_1
  - tk=8.6.13=noxft_h0dc03b3_103
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.1=py311h19352d5_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=hca56bd8_2
  - xcb-util-image=0.4.0=h5c728e9_2
  - xcb-util-keysyms=0.4.1=h5c728e9_0
  - xcb-util-renderutil=0.3.10=h5c728e9_0
  - xcb-util-wm=0.4.2=h5c728e9_0
  - xkeyboard-config=2.46=he30d5cf_0
  - xorg-libice=1.1.2=h86ecc28_0
  - xorg-libsm=1.2.6=h0808dbd_0
  - xorg-libx11=1.8.13=h63a1b12_0
  - xorg-libxau=1.0.12=he30d5cf_1
  - xorg-libxcomposite=0.4.7=he30d5cf_0
  - xorg-libxdamage=1.1.6=h86ecc28_0
  - xorg-libxdmcp=1.1.5=he30d5cf_1
  - xorg-libxext=1.3.7=he30d5cf_0
  - xorg-libxfixes=6.0.2=he30d5cf_0
  - xorg-libxrender=0.9.12=h86ecc28_0
  - xorg-libxshmfence=1.3.3=h86ecc28_0
  - xorg-libxxf86vm=1.1.7=he30d5cf_0
  - zlib=1.3.1=h86ecc28_2
  - zlib-ng=2.3.3=ha7cb516_1
  - zstd=1.5.7=h85ac4a6_6
  - pip:
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anywidget==0.9.21
    - asttokens==3.0.1
    - attrs==25.4.0
    - biopython==1.86
    - biotite==1.6.0
    - biotraj==1.2.2
    - certifi==2026.1.4
    - cffi==2.0.0
    - cloudpathlib==0.23.0
    - comm==0.2.3
    - cryptography==46.0.5
    - decorator==5.2.1
    - duckdb==1.4.4
    - eval_type_backport==0.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - frozenlist==1.8.0
    - fsspec==2026.2.0
    - gcsfs==2026.2.0
    - gemmi==0.7.4
    - google-api-core==2.30.0
    - google-auth==2.48.0
    - google-auth-oauthlib==1.2.4
    - google-cloud-core==2.5.0
    - google-cloud-storage==3.9.0
    - google-cloud-storage-control==1.10.0
    - google-crc32c==1.8.0
    - google-resumable-media==2.8.0
    - googleapis-common-protos==1.72.0
    - grpc-google-iam-v1==0.14.3
    - grpcio==1.78.0
    - grpcio-status==1.78.0
    - idna==3.11
    - ipython==9.10.0
    - ipython_pygments_lexers==1.1.1
    - ipywidgets==8.1.8
    - jedi==0.19.2
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - jupyter_core==5.9.1
    - jupyterlab_widgets==3.0.16
    - matplotlib-inline==0.2.1
    - mmcif==1.1.0
    - mols2grid==2.2.0
    - msgpack==1.1.2
    - multidict==6.7.1
    - narwhals==2.16.0
    - nbformat==5.10.4
    - networkx==3.6.1
    - oauthlib==3.3.1
    - omegaconf==2.3.0
    - parso==0.8.6
    - pexpect==4.9.0
    - platformdirs==4.9.2
    - plinder==0.2.26
    - plotly==6.5.2
    - posebusters==0.6.4
    - prompt_toolkit==3.0.52
    - propcache==0.4.1
    - proto-plus==1.27.1
    - protobuf==6.33.5
    - psygnal==0.15.1
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pyarrow==23.0.1
    - pyasn1==0.6.2
    - pyasn1_modules==0.4.2
    - pycparser==3.0
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - referencing==0.37.0
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rpds-py==0.30.0
    - rsa==4.9.1
    - scipy==1.17.0
    - stack-data==0.6.3
    - tqdm==4.67.3
    - traitlets==5.14.3
    - typing-inspection==0.4.2
    - urllib3==2.6.3
    - wcwidth==0.6.0
    - widgetsnbextension==4.0.15
    - yarl==1.22.0
